# Generated by Django 2.2 on 2021-05-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_haven_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comms_liked', to='plant_haven_app.User'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants_owned', to='plant_haven_app.User'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='wanted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants_wanted', to='plant_haven_app.User'),
        ),
    ]
