# Generated by Django 2.2 on 2021-05-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_haven_app', '0002_auto_20210516_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_image',
            field=models.ImageField(blank=True, upload_to='plant_image'),
        ),
    ]
