# Generated by Django 2.2 on 2021-04-28 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy_helper_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='taken_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_taken', to='handy_helper_app.User'),
        ),
    ]
