# Generated by Django 2.2 on 2021-04-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy_helper_app', '0003_auto_20210428_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cust_service_job',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='manufacturing_job',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='other_job',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='tech_job',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
