# Generated by Django 2.2 on 2021-04-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy_helper_app', '0004_auto_20210428_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cust_service_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='manufacturing_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='tech_job',
            field=models.BooleanField(default=False),
        ),
    ]
