# Generated by Django 2.2 on 2021-04-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handy_helper_app', '0005_auto_20210428_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='cust_service_job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='manufacturing_job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='other_job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tech_job',
        ),
    ]
